### ISSUE TITLE
Error while decrypting AccountData.json

### ISSUE THREAD

**Issue by askjdg123** [ic3w0lf22/RAMDecrypt#3]
Unhandled Exception: System.Security.Cryptography.CryptographicException: Key not valid for use in specified state.

   at System.Security.Cryptography.ProtectedData.Unprotect(Byte[] encryptedData, Byte[] optionalEntropy, DataProtectionScope scope)
   at RAMDecrypt.Program.Main(String[] args)

**Comment by APPLEJUICE529** [comment]
Im getting this error now, did you ever find out how to fix it?

**Comment by valzevox** [comment]
The error CryptographicException: Key not valid for use in specified state occurs because the system refuses to decrypt due to the absence of a valid security key.

Here’s how it works: In the Program.cs file, data is processed through the ProtectedData.Unprotect function with the parameter DataProtectionScope.CurrentUser. This parameter uses Windows DPAPI (Data Protection API) to tightly bind the data to the Windows user account executing the code.

But here’s the issue: The decryption key is generated by the operating system based on the login credentials of the original Windows account. If the file you’re loading (AccountData.json) was encrypted on another computer or under a different Windows account, the current machine won’t have the secret key needed to unlock it.

So what happened is this: The system detected that the decryption environment doesn’t match the environment in which the data was originally encrypted. To open this file, you must run the program on the exact same computer and under the exact same Windows account that performed the original encryption.
